# Jekyll configuration

name: 도쿄에 서식중인 양산형 개발자(공사중)
description: 일본에서 IT개발자로 살아가기

# Url is currently only used only for the RSS feed in feed.xml
url: https://buzzricksons.github.io

# For Local
# url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

share:
  facebook: buzzricksons
  twitter: yodarickson
  gplus:
  linkedin:
  pinterest:
  email: hcgoon@gmail.com

social:
  github: buzzricksons
  stackoverflow:
  stackoverflow:
  linkedin:
  instagram: buzzricksons
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-92791840-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: buzzricksons
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

gems:
  - jekyll-seo-tag
